// This file is auto-generated by @hey-api/openapi-ts

export const AddToQueueSchema = {
    properties: {
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        desc: {
            type: 'string',
            title: 'Desc'
        }
    },
    type: 'object',
    required: ['user_id', 'desc'],
    title: 'AddToQueue'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const EventAdminCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        price: {
            type: 'number',
            title: 'Price'
        },
        location: {
            type: 'string',
            title: 'Location'
        },
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        end_time: {
            type: 'string',
            format: 'date-time',
            title: 'End Time'
        },
        tags: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        pictures: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pictures'
        },
        visibility: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visibility',
            default: 'private'
        },
        organizer_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Organizer Id'
        },
        count_attendees: {
            type: 'integer',
            title: 'Count Attendees',
            default: 0
        },
        capacity: {
            type: 'integer',
            title: 'Capacity',
            default: 1
        },
        tickets_left: {
            type: 'integer',
            title: 'Tickets Left',
            default: 1
        }
    },
    type: 'object',
    required: ['name', 'description', 'price', 'location', 'start_time', 'end_time'],
    title: 'EventAdminCreate'
} as const;

export const EventListSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        price: {
            type: 'number',
            title: 'Price'
        },
        location: {
            type: 'string',
            title: 'Location'
        },
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        end_time: {
            type: 'string',
            format: 'date-time',
            title: 'End Time'
        },
        tags: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        pictures: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pictures'
        },
        organizer_id: {
            type: 'string',
            title: 'Organizer Id'
        }
    },
    type: 'object',
    required: ['id', 'name', 'description', 'price', 'location', 'start_time', 'end_time', 'organizer_id'],
    title: 'EventList'
} as const;

export const EventUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        start_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        tags: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        pictures: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pictures'
        },
        visibility: {
            type: 'string',
            title: 'Visibility'
        },
        state: {
            type: 'string',
            title: 'State'
        }
    },
    type: 'object',
    required: ['visibility', 'state'],
    title: 'EventUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModQueueSchema = {
    properties: {
        req: {
            type: 'integer',
            title: 'Req'
        },
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        desc: {
            type: 'string',
            title: 'Desc'
        },
        date_created: {
            type: 'string',
            format: 'date-time',
            title: 'Date Created'
        }
    },
    type: 'object',
    required: ['req', 'user_id'],
    title: 'ModQueue'
} as const;

export const ReviewAddSchema = {
    properties: {
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        event_id: {
            type: 'integer',
            title: 'Event Id'
        },
        desc: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Desc'
        },
        star: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Star'
        },
        date_created: {
            type: 'string',
            format: 'date-time',
            title: 'Date Created'
        }
    },
    type: 'object',
    required: ['user_id', 'event_id', 'date_created'],
    title: 'ReviewAdd'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        pronouns: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pronouns'
        },
        username: {
            type: 'string',
            maxLength: 255,
            title: 'Username'
        },
        date_of_birth: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Of Birth'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student'
        },
        id: {
            type: 'string',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'username', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            title: 'Username'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        first_name: {
            type: 'string',
            maxLength: 255,
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            maxLength: 255,
            title: 'Last Name'
        },
        pronouns: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pronouns'
        },
        date_of_birth: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Of Birth'
        }
    },
    type: 'object',
    required: ['username', 'email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'student', 'organizer'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        pronouns: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pronouns'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UserUpdatePassword'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;