// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { EventsCreateEventData, EventsCreateEventResponse, EventsReadEventData, EventsReadEventResponse, EventsUpdateEventData, EventsUpdateEventResponse, EventsPatchEventData, EventsPatchEventResponse, EventsDeleteEventData, EventsDeleteEventResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse } from './types.gen';

export class EventsService {
    /**
     * Create Event
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static createEvent(data: EventsCreateEventData): CancelablePromise<EventsCreateEventResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/clank/events',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Event
     * @param data The data for the request.
     * @param data.eventId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readEvent(data: EventsReadEventData): CancelablePromise<EventsReadEventResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/clank/events/{event_id}',
            path: {
                event_id: data.eventId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Event
     * @param data The data for the request.
     * @param data.eventId
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static updateEvent(data: EventsUpdateEventData): CancelablePromise<EventsUpdateEventResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/clank/events/{event_id}',
            path: {
                event_id: data.eventId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Patch Event
     * @param data The data for the request.
     * @param data.eventId
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static patchEvent(data: EventsPatchEventData): CancelablePromise<EventsPatchEventResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/clank/events/{event_id}',
            path: {
                event_id: data.eventId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Event
     * @param data The data for the request.
     * @param data.eventId
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteEvent(data: EventsDeleteEventData): CancelablePromise<EventsDeleteEventResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/clank/events/{event_id}',
            path: {
                event_id: data.eventId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 Compatible Token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/clank/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/clank/login/test-token'
        });
    }
}