// This file is auto-generated by @hey-api/openapi-ts

export type AddToQueue = {
  user_id: string
  desc: string
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type EventAdminCreate = {
  name: string
  description: string
  price: number
  location: string
  start_time: string
  end_time: string
  tags?: string | null
  pictures?: string | null
  visibility?: string | null
  organizer_id?: string | null
  count_attendees?: number
  capacity?: number
  tickets_left?: number
}

export type EventList = {
  id: number
  name: string
  description: string
  price: number
  location: string
  start_time: string
  end_time: string
  tags?: string | null
  pictures?: string | null
  organizer_id: string
}

export type EventUpdate = {
  name?: string | null
  description?: string | null
  price?: number | null
  location?: string | null
  start_time?: string | null
  end_time?: string | null
  tags?: string | null
  pictures?: string | null
  visibility: string
  state: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  message: string
}

export type ModQueue = {
  req: number
  user_id: string
  desc?: string
  date_created?: string
}

export type ReviewAdd = {
  user_id: string
  event_id: number
  desc?: string | null
  star?: number | null
  date_created: string
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UserPublic = {
  email: string
  first_name?: string | null
  last_name?: string | null
  pronouns?: string | null
  username: string
  date_of_birth?: string | null
  role?: UserRole
  id: string
}

export type UserRegister = {
  username: string
  email: string
  password: string
  first_name?: string
  last_name?: string
  pronouns?: string | null
  date_of_birth?: string | null
}

export type UserRole = 'admin' | 'student' | 'organizer'

export type UserUpdate = {
  email?: string | null
  first_name?: string | null
  last_name?: string | null
  pronouns?: string | null
}

export type UserUpdatePassword = {
  current_password: string
  new_password: string
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type AdminUtilitiesSeedDatabaseResponse = unknown

export type ToolsGetNumUsersResponse = unknown

export type ToolsGetNumOrganizersResponse = unknown

export type ToolsGetPronounCountResponse = unknown

export type ToolsGetAverageAgeResponse = unknown

export type ToolsGetEventAverageAgeData = {
  eventId: number
}

export type ToolsGetEventAverageAgeResponse = unknown

export type ToolsGetAttendeesListData = {
  eventId: number
}

export type ToolsGetAttendeesListResponse = unknown

export type ToolsGetAllEventsResponse = unknown

export type CalendarGetUserCalendarResponse = Array<EventList>

export type CalendarDeleteEventCalendarData = {
  eventId: number
}

export type CalendarDeleteEventCalendarResponse = unknown

export type CalendarSaveEventCalendarData = {
  eventId: number
}

export type CalendarSaveEventCalendarResponse = unknown

export type EventsCreateEventData = {
  requestBody: EventAdminCreate
}

export type EventsCreateEventResponse = unknown

export type EventsListPublicEventsResponse = Array<EventList>

export type EventsListEventsResponse = unknown

export type EventsRandomButtonResponse = unknown

export type EventsGetTicketsResponse = unknown

export type EventsReadPublicEventData = {
  eventId: number
}

export type EventsReadPublicEventResponse = unknown

export type EventsReadEventData = {
  eventId: number
}

export type EventsReadEventResponse = unknown

export type EventsUpdateEventData = {
  eventId: number
  requestBody: EventUpdate
}

export type EventsUpdateEventResponse = unknown

export type EventsPatchEventData = {
  eventId: number
  requestBody: EventUpdate
}

export type EventsPatchEventResponse = unknown

export type EventsDeleteEventData = {
  eventId: number
}

export type EventsDeleteEventResponse = unknown

export type EventsAddTicketData = {
  eventId: number
  ticket: string
}

export type EventsAddTicketResponse = unknown

export type EventsRemoveTicketData = {
  eventId: number
}

export type EventsRemoveTicketResponse = unknown

export type EventsAddReviewData = {
  requestBody: ReviewAdd
}

export type EventsAddReviewResponse = unknown

export type EventsRemoveReviewData = {
  reviewId: number
}

export type EventsRemoveReviewResponse = unknown

export type EventsGetEventReviewsData = {
  eventId: number
}

export type EventsGetEventReviewsResponse = unknown

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type ToolsGetAllUsersResponse = unknown

export type ToolsGetAllOrganizersResponse = unknown

export type ToolsDeleteUserData = {
  userId: string
}

export type ToolsDeleteUserResponse = unknown

export type ToolsGetQueueResponse = Array<ModQueue>

export type ToolsAddReportData = {
  requestBody: AddToQueue
}

export type ToolsAddReportResponse = ModQueue

export type ToolsDeleteReportData = {
  req: number
}

export type ToolsDeleteReportResponse = ModQueue

export type UsersCreateUserData = {
  requestBody: UserRegister
  userRole: string
}

export type UsersCreateUserResponse = Token

export type UsersGetMeUserResponse = UserPublic

export type UsersDeleteMeResponse = Message

export type UsersGetUserData = {
  userId: string
}

export type UsersGetUserResponse = unknown

export type UsersUpdatePasswordData = {
  requestBody: UserUpdatePassword
}

export type UsersUpdatePasswordResponse = Message

export type UsersUpdateMeData = {
  requestBody: UserUpdate
}

export type UsersUpdateMeResponse = UserPublic
