// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type EventCreate = {
    name: string;
    description: string;
    price: number;
    location: string;
    start_time: string;
    end_time: string;
    tags?: (string | null);
    pictures?: (string | null);
};

export type EventUpdate = {
    name?: (string | null);
    description?: (string | null);
    price?: (number | null);
    location?: (string | null);
    start_time?: (string | null);
    end_time?: (string | null);
    tags?: (string | null);
    pictures?: (string | null);
    visibility: string;
    state: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserPublic = {
    email: string;
    first_name?: (string | null);
    last_name?: (string | null);
    pronouns?: (string | null);
    username: string;
    role?: UserRole;
    id: string;
};

export type UserRole = 'admin' | 'student' | 'organizer';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type EventsCreateEventData = {
    requestBody: EventCreate;
};

export type EventsCreateEventResponse = (unknown);

export type EventsReadEventData = {
    eventId: number;
};

export type EventsReadEventResponse = (unknown);

export type EventsUpdateEventData = {
    eventId: number;
    requestBody: EventUpdate;
};

export type EventsUpdateEventResponse = (unknown);

export type EventsPatchEventData = {
    eventId: number;
    requestBody: EventUpdate;
};

export type EventsPatchEventResponse = (unknown);

export type EventsDeleteEventData = {
    eventId: number;
    requestBody: EventUpdate;
};

export type EventsDeleteEventResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);