/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventCreationRouteImport } from './routes/event-creation'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as EventsEventIdEditRouteImport } from './routes/events.$eventId.edit'
import { Route as EventsEventIdAnalyticsRouteImport } from './routes/events.$eventId.analytics'

const SignupLazyRouteImport = createFileRoute('/signup')()
const PaymentSuccessLazyRouteImport = createFileRoute('/payment-success')()

const SignupLazyRoute = SignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))
const PaymentSuccessLazyRoute = PaymentSuccessLazyRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/payment-success.lazy').then((d) => d.Route),
)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/purchase.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventCreationRoute = EventCreationRouteImport.update({
  id: '/event-creation',
  path: '/event-creation',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdAnalyticsRoute = EventsEventIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => EventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/event-creation': typeof EventCreationRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/purchase': typeof PurchaseRoute
  '/tickets': typeof TicketsRoute
  '/payment-success': typeof PaymentSuccessLazyRoute
  '/signup': typeof SignupLazyRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/$eventId/analytics': typeof EventsEventIdAnalyticsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/event-creation': typeof EventCreationRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/purchase': typeof PurchaseRoute
  '/tickets': typeof TicketsRoute
  '/payment-success': typeof PaymentSuccessLazyRoute
  '/signup': typeof SignupLazyRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/$eventId/analytics': typeof EventsEventIdAnalyticsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/event-creation': typeof EventCreationRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/purchase': typeof PurchaseRoute
  '/tickets': typeof TicketsRoute
  '/payment-success': typeof PaymentSuccessLazyRoute
  '/signup': typeof SignupLazyRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/$eventId/analytics': typeof EventsEventIdAnalyticsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/event-creation'
    | '/events'
    | '/login'
    | '/purchase'
    | '/tickets'
    | '/payment-success'
    | '/signup'
    | '/events/$eventId'
    | '/events/$eventId/analytics'
    | '/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/event-creation'
    | '/events'
    | '/login'
    | '/purchase'
    | '/tickets'
    | '/payment-success'
    | '/signup'
    | '/events/$eventId'
    | '/events/$eventId/analytics'
    | '/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/event-creation'
    | '/events'
    | '/login'
    | '/purchase'
    | '/tickets'
    | '/payment-success'
    | '/signup'
    | '/events/$eventId'
    | '/events/$eventId/analytics'
    | '/events/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  EventCreationRoute: typeof EventCreationRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PurchaseRoute: typeof PurchaseRoute
  TicketsRoute: typeof TicketsRoute
  PaymentSuccessLazyRoute: typeof PaymentSuccessLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-creation': {
      id: '/event-creation'
      path: '/event-creation'
      fullPath: '/event-creation'
      preLoaderRoute: typeof EventCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$eventId/edit': {
      id: '/events/$eventId/edit'
      path: '/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/analytics': {
      id: '/events/$eventId/analytics'
      path: '/analytics'
      fullPath: '/events/$eventId/analytics'
      preLoaderRoute: typeof EventsEventIdAnalyticsRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
  }
}

interface EventsEventIdRouteChildren {
  EventsEventIdAnalyticsRoute: typeof EventsEventIdAnalyticsRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdAnalyticsRoute: EventsEventIdAnalyticsRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  EventCreationRoute: EventCreationRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  PurchaseRoute: PurchaseRoute,
  TicketsRoute: TicketsRoute,
  PaymentSuccessLazyRoute: PaymentSuccessLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
