name: Validate Code Quality Using Pylint

on:
    push:
        branches: [backend]
    pull_request:
        branches: [main, backend]

jobs:
    validate-openapi:
        name: Pylint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5
            
            - name: Set Up Python
              uses: actions/setup-python@v6
              with:
                    python-version: '3.13.7'
            
            - name: Activate Virtual Environment
              run: |
                    cd backend
                    python -m venv .venv
                    source .venv/bin/activate
            
            - name: Install Dependencies
              run: |
                    cd backend
                    pip install -r requirements.txt
                    pip install pylint

            - name: Start Pylint
              id: pylint
              run: |
                    cd backend
                    python -m pylint app/ --disable=missing-function-docstring,missing-class-docstring,missing-module-docstring --exit-zero | tee pylint.txt
                    SCORE=$(grep "Your code has been rated at" pylint.txt | sed -E 's/.* ([0-9]+(\.[0-9]+)\/.*/\1/)'
                    echo "score=$SCORE" >> $GITHUB_OUTPUT

            - name: Compare minimum score
              run: |
                THRESHOLD=8.5
                SCORE=${{ steps.pylint.outputs.score }}
                
                if (( $(echo "$SCORE < $THRESHOLD" | bc -l) )); then
                  echo "Pylint score is too low."
                  exit 1
                else
                  echo "Pylint score meets threshold."
                fi